server:
  port: 8080

spring:
  application:
    name: day-01-fat-controller-to-clean
  
  # Disable JPA for in-memory repository
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  
  # Logging configuration
  logging:
    level:
      com.example.app: DEBUG
      org.springframework.web: DEBUG
    pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
